# Generated by Django 5.2.17 on 2026-08-29 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='URL-safe slug, e.g. "data-science"', max_length=64, unique=True)),
                ('title', models.CharField(help_text='Display title, e.g. "Data Science"', max_length=128)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (Material Symbol name or emoji)', max_length=64)),
                ('color', models.CharField(blank=True, help_text='Track accent hex, e.g. "#059669"', max_length=7)),
                ('track_code', models.CharField(blank=True, default='', help_text='Short code, e.g. "TS-01", "AI-01"', max_length=10)),
                ('character_image', models.CharField(blank=True, default='', help_text='Path or URL to theme character image', max_length=500)),
                ('is_published', models.BooleanField(default=True, help_text='Toggle track visibility from admin')),
            ],
            options={
                'ordering': ['track_code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CapstoneSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(help_text="URL to the user's GitHub repository")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_feedback', models.TextField(blank=True, help_text='Markdown formatted AI feedback', null=True)),
                ('score', models.IntegerField(blank=True, help_text='0-100 score', null=True)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_submissions', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_submissions', to='learn.domain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Level number 1-10')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('quiz_data', models.JSONField(blank=True, help_text='List of 5 dicts: {question, options, correct_index}', null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='learn.domain')),
            ],
            options={
                'ordering': ['domain', 'number'],
                'unique_together': {('domain', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Display order within the level')),
                ('title', models.CharField(max_length=256)),
                ('content_md', models.TextField(blank=True, help_text='Lesson body in Markdown')),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('coins_reward', models.PositiveIntegerField(default=5)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Must complete to unlock next level')),
                ('illustration_url', models.URLField(blank=True, help_text='Optional illustration image URL for visual lesson headers', null=True)),
                ('lesson_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('quiz', 'Quiz'), ('boss', 'Boss Quiz')], default='theory', help_text='Category: theory, lab, quiz, or boss', max_length=20)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learn.level')),
            ],
            options={
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DomainProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=True)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('highest_unlocked_level', models.PositiveSmallIntegerField(default=1)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learn.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain Progress',
                'verbose_name_plural': 'Domain Progress',
                'unique_together': {('user', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('lessons_completed', models.ManyToManyField(blank=True, related_name='completed_by', to='learn.lesson')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learn.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Level Progress',
                'verbose_name_plural': 'Level Progress',
                'unique_together': {('user', 'level')},
            },
        ),
    ]
