# Generated by Django 5.2.17 on 2026-08-21 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='URL-safe slug, e.g. "data-science"', max_length=64, unique=True)),
                ('title', models.CharField(help_text='Display title, e.g. "Data Science"', max_length=128)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (Material Symbol name or emoji)', max_length=64)),
                ('color', models.CharField(blank=True, help_text='Track accent hex, e.g. "#059669"', max_length=7)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Level number 1-10')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='learn.domain')),
            ],
            options={
                'ordering': ['domain', 'number'],
                'unique_together': {('domain', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Display order within the level')),
                ('title', models.CharField(max_length=256)),
                ('content_md', models.TextField(blank=True, help_text='Lesson body in Markdown')),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('coins_reward', models.PositiveIntegerField(default=5)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Must complete to unlock next level')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learn.level')),
            ],
            options={
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DomainProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=True)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learn.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain Progress',
                'verbose_name_plural': 'Domain Progress',
                'unique_together': {('user', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('lessons_completed', models.ManyToManyField(blank=True, related_name='completed_by', to='learn.lesson')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learn.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Level Progress',
                'verbose_name_plural': 'Level Progress',
                'unique_together': {('user', 'level')},
            },
        ),
    ]
