# Generated by Django 5.2.17 on 2026-08-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='illustration_url',
            field=models.URLField(blank=True, help_text='Optional illustration image URL for visual lesson headers', null=True),
        ),
    ]
