# Generated by Django 5.2.17 on 2026-08-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_lesson_illustration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainprogress',
            name='highest_unlocked_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='level',
            name='quiz_data',
            field=models.JSONField(blank=True, help_text='List of 5 dicts: {question, options, correct_index}', null=True),
        ),
    ]
