# Generated by Django 5.2.17 on 2026-08-24 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_domainprogress_highest_unlocked_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(help_text="URL to the user's GitHub repository")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_feedback', models.TextField(blank=True, help_text='Markdown formatted AI feedback', null=True)),
                ('score', models.IntegerField(blank=True, help_text='0-100 score', null=True)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_submissions', to='learn.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
