# Generated by Django 5.2.17 on 2026-08-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_capstonesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='character_image',
            field=models.CharField(blank=True, default='', help_text='Path or URL to theme character image', max_length=500),
        ),
        migrations.AddField(
            model_name='domain',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Toggle track visibility from admin'),
        ),
        migrations.AddField(
            model_name='domain',
            name='track_code',
            field=models.CharField(blank=True, default='', help_text='Short code, e.g. "TS-01", "AI-01"', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('quiz', 'Quiz'), ('boss', 'Boss Quiz')], default='theory', help_text='Category: theory, lab, quiz, or boss', max_length=20),
        ),
    ]
